apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kkos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kkos
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kkos
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kkos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kkos
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tnuf-tenant/rhtap-demo-app/hacbs-test-project-kkos@sha256:122e0dfaf4c142968f8c0a63753e697d68b118ea49f844c636d8377855279650
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
