apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kkos
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tnuf-tenant/rhtap-demo-app/hacbs-test-project-kkos@sha256:122e0dfaf4c142968f8c0a63753e697d68b118ea49f844c636d8377855279650
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
